algoritmo "vetorPosOuNeg"
// Função : ) Crie um algoritmo que possa armazenar dez números que podem ser positivos ou negativos,
// após o cadastro o algoritmo deverá imprimir todos os números negativos primeiro e logo em seguida
// imprimir todos os números positivos.

// Cadastro
// -10
// 10
// -20

// Impressão Negativos
// -10
// -20

// Impressão Positivos
// 10

// Autor : Guilherme
// Data : 18/10/2021
// Seção de Declarações 
var

inicio
// Seção de Comandos 
fimalgoritmo
